apiVersion: v1
kind: Service
metadata:
  labels:
    name: docker-maven-demo-ingress
  name: docker-maven-demo-ingress
spec:
  ports:
    - port: 8080
  selector:
    app: docker-maven-demo-ingress

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: docker-maven-demo-ingress
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-maven-demo-ingress
    spec:
      imagePullSecrets: 
      - name: landa-aliyun-secret
      containers:
      - name: docker-maven-demo-ingress
        image: registry.cn-shanghai.aliyuncs.com/landasoft/landa-mas:spring-boot-docker
#        image: harbor.k8s.landaudev.com/demo/spring-boot-docker
        imagePullPolicy: Always#三个选择Always、Never、IfNotPresent，每次启动时检查和更新（从registery）images的策略， 
                               # Always，每次都检查 
                               # Never，每次都不检查（不管本地是否有） 
                               # IfNotPresent，如果本地有就不检查，如果没有就拉取 
        ports:
        - containerPort: 8080

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: docker-maven-demo-ingress
spec:
  rules:
  - host: docker-maven-demo-ingress.alik8s.landaudev.com
    http:
      paths:
      - path: /
        backend:
          serviceName: docker-maven-demo-ingress
          servicePort: 8080

