server:
  port: 5758

spring:
  profiles:
    active: dev   # @activatedProperties@ 开发过程中可以指定配置环境，实际请使用后面的配置，以便构建使用指定配置构建代码包
  mvc:
    throw-exception-if-no-handler-found: true
  application:
    name: landa-mas-docker-demo    # 项目名称尽量用小写
#暴露actuator端点    
management:
  endpoints:
    web:
      exposure:
        include: '*'
